//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;

public class LongDoubleVector : IDisposable, IEnumerable
    , IEnumerable<SWIGTYPE_p_long_double>
{
    protected bool swigCMemOwn;
    private HandleRef swigCPtr;

    internal LongDoubleVector(IntPtr cPtr, bool cMemoryOwn)
    {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = new HandleRef(this, cPtr);
    }

    public LongDoubleVector(ICollection c) : this()
    {
        if (c == null)
            throw new ArgumentNullException("c");
        foreach (SWIGTYPE_p_long_double element in c)
        {
            Add(element);
        }
    }

    public LongDoubleVector() : this(CoolPropPINVOKE.new_LongDoubleVector__SWIG_0(), true)
    {
    }

    public LongDoubleVector(LongDoubleVector other)
        : this(CoolPropPINVOKE.new_LongDoubleVector__SWIG_1(getCPtr(other)), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public LongDoubleVector(int capacity) : this(CoolPropPINVOKE.new_LongDoubleVector__SWIG_2(capacity), true)
    {
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public bool IsFixedSize
    {
        get { return false; }
    }

    public bool IsReadOnly
    {
        get { return false; }
    }

    public SWIGTYPE_p_long_double this[int index]
    {
        get { return getitem(index); }
        set { setitem(index, value); }
    }

    public int Capacity
    {
        get { return (int) capacity(); }
        set
        {
            if (value < size())
                throw new ArgumentOutOfRangeException("Capacity");
            reserve((uint) value);
        }
    }

    public int Count
    {
        get { return (int) size(); }
    }

    public bool IsSynchronized
    {
        get { return false; }
    }

    public virtual void Dispose()
    {
        lock (this)
        {
            if (swigCPtr.Handle != IntPtr.Zero)
            {
                if (swigCMemOwn)
                {
                    swigCMemOwn = false;
                    CoolPropPINVOKE.delete_LongDoubleVector(swigCPtr);
                }
                swigCPtr = new HandleRef(null, IntPtr.Zero);
            }
            GC.SuppressFinalize(this);
        }
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return new LongDoubleVectorEnumerator(this);
    }

    IEnumerator<SWIGTYPE_p_long_double> IEnumerable<SWIGTYPE_p_long_double>.GetEnumerator()
    {
        return new LongDoubleVectorEnumerator(this);
    }

    internal static HandleRef getCPtr(LongDoubleVector obj)
    {
        return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
    }

    ~LongDoubleVector()
    {
        Dispose();
    }

    public void CopyTo(SWIGTYPE_p_long_double[] array)
    {
        CopyTo(0, array, 0, Count);
    }

    public void CopyTo(SWIGTYPE_p_long_double[] array, int arrayIndex)
    {
        CopyTo(0, array, arrayIndex, Count);
    }

    public void CopyTo(int index, SWIGTYPE_p_long_double[] array, int arrayIndex, int count)
    {
        if (array == null)
            throw new ArgumentNullException("array");
        if (index < 0)
            throw new ArgumentOutOfRangeException("index", "Value is less than zero");
        if (arrayIndex < 0)
            throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
        if (count < 0)
            throw new ArgumentOutOfRangeException("count", "Value is less than zero");
        if (array.Rank > 1)
            throw new ArgumentException("Multi dimensional array.", "array");
        if (index + count > Count || arrayIndex + count > array.Length)
            throw new ArgumentException("Number of elements to copy is too large.");
        for (var i = 0; i < count; i++)
            array.SetValue(getitemcopy(index + i), arrayIndex + i);
    }

    public LongDoubleVectorEnumerator GetEnumerator()
    {
        return new LongDoubleVectorEnumerator(this);
    }

    public void Clear()
    {
        CoolPropPINVOKE.LongDoubleVector_Clear(swigCPtr);
    }

    public void Add(SWIGTYPE_p_long_double x)
    {
        CoolPropPINVOKE.LongDoubleVector_Add(swigCPtr, SWIGTYPE_p_long_double.getCPtr(x));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    private uint size()
    {
        var ret = CoolPropPINVOKE.LongDoubleVector_size(swigCPtr);
        return ret;
    }

    private uint capacity()
    {
        var ret = CoolPropPINVOKE.LongDoubleVector_capacity(swigCPtr);
        return ret;
    }

    private void reserve(uint n)
    {
        CoolPropPINVOKE.LongDoubleVector_reserve(swigCPtr, n);
    }

    private SWIGTYPE_p_long_double getitemcopy(int index)
    {
        var ret = new SWIGTYPE_p_long_double(CoolPropPINVOKE.LongDoubleVector_getitemcopy(swigCPtr, index), true);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    private SWIGTYPE_p_long_double getitem(int index)
    {
        var ret = new SWIGTYPE_p_long_double(CoolPropPINVOKE.LongDoubleVector_getitem(swigCPtr, index), false);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    private void setitem(int index, SWIGTYPE_p_long_double val)
    {
        CoolPropPINVOKE.LongDoubleVector_setitem(swigCPtr, index, SWIGTYPE_p_long_double.getCPtr(val));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void AddRange(LongDoubleVector values)
    {
        CoolPropPINVOKE.LongDoubleVector_AddRange(swigCPtr, getCPtr(values));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public LongDoubleVector GetRange(int index, int count)
    {
        var cPtr = CoolPropPINVOKE.LongDoubleVector_GetRange(swigCPtr, index, count);
        var ret = (cPtr == IntPtr.Zero) ? null : new LongDoubleVector(cPtr, true);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    public void Insert(int index, SWIGTYPE_p_long_double x)
    {
        CoolPropPINVOKE.LongDoubleVector_Insert(swigCPtr, index, SWIGTYPE_p_long_double.getCPtr(x));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void InsertRange(int index, LongDoubleVector values)
    {
        CoolPropPINVOKE.LongDoubleVector_InsertRange(swigCPtr, index, getCPtr(values));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void RemoveAt(int index)
    {
        CoolPropPINVOKE.LongDoubleVector_RemoveAt(swigCPtr, index);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void RemoveRange(int index, int count)
    {
        CoolPropPINVOKE.LongDoubleVector_RemoveRange(swigCPtr, index, count);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public static LongDoubleVector Repeat(SWIGTYPE_p_long_double value, int count)
    {
        var cPtr = CoolPropPINVOKE.LongDoubleVector_Repeat(SWIGTYPE_p_long_double.getCPtr(value), count);
        var ret = (cPtr == IntPtr.Zero) ? null : new LongDoubleVector(cPtr, true);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
        return ret;
    }

    public void Reverse()
    {
        CoolPropPINVOKE.LongDoubleVector_Reverse__SWIG_0(swigCPtr);
    }

    public void Reverse(int index, int count)
    {
        CoolPropPINVOKE.LongDoubleVector_Reverse__SWIG_1(swigCPtr, index, count);
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    public void SetRange(int index, LongDoubleVector values)
    {
        CoolPropPINVOKE.LongDoubleVector_SetRange(swigCPtr, index, getCPtr(values));
        if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    }

    // Type-safe enumerator
    /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
    /// whenever the collection is modified. This has been done for changes in the size of the
    /// collection but not when one of the elements of the collection is modified as it is a bit
    /// tricky to detect unmanaged code that modifies the collection under our feet.
    public sealed class LongDoubleVectorEnumerator : IEnumerator
        , IEnumerator<SWIGTYPE_p_long_double>
    {
        private readonly LongDoubleVector collectionRef;
        private readonly int currentSize;
        private int currentIndex;
        private object currentObject;

        public LongDoubleVectorEnumerator(LongDoubleVector collection)
        {
            collectionRef = collection;
            currentIndex = -1;
            currentObject = null;
            currentSize = collectionRef.Count;
        }

        // Type-unsafe IEnumerator.Current
        object IEnumerator.Current
        {
            get { return Current; }
        }

        public bool MoveNext()
        {
            var size = collectionRef.Count;
            var moveOkay = (currentIndex + 1 < size) && (size == currentSize);
            if (moveOkay)
            {
                currentIndex++;
                currentObject = collectionRef[currentIndex];
            }
            else
            {
                currentObject = null;
            }
            return moveOkay;
        }

        public void Reset()
        {
            currentIndex = -1;
            currentObject = null;
            if (collectionRef.Count != currentSize)
            {
                throw new InvalidOperationException("Collection modified.");
            }
        }

        // Type-safe iterator Current
        public SWIGTYPE_p_long_double Current
        {
            get
            {
                if (currentIndex == -1)
                    throw new InvalidOperationException("Enumeration not started.");
                if (currentIndex > currentSize - 1)
                    throw new InvalidOperationException("Enumeration finished.");
                if (currentObject == null)
                    throw new InvalidOperationException("Collection modified.");
                return (SWIGTYPE_p_long_double) currentObject;
            }
        }

        public void Dispose()
        {
            currentIndex = -1;
            currentObject = null;
        }
    }
}